name: staffapp
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.1.0+1
  cloud_firestore: ^0.13.5
  flutter_datetime_picker: ^1.3.8
  intl: ^0.16.1
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
